id: a1f65f32f91546be9bcfa04f2be763b5
initial_creation_type: ocr
source_metadata:
  volumes:
    0d718794df6644e292f2dd5949f488a4:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ལྷན་ཅིག་སྐྱེས་པའི་གླུ།
      total_pages: 1953
      volume_number: 27
